
spring:
  config:
    import: optional:configserver:http://localhost:8888

  cloud:
    config:
      enabled: true

  application:
    name: authentication-service

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
